name: API tests

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  smoke:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Run smoke tests
        run: mvn clean test -Dgroups=smoke

  regression:
    runs-on: self-hosted
    needs: smoke
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Run regression tests
        run: mvn clean test -Dgroups=regression

  e2e:
    runs-on: self-hosted
    needs: regression
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Run e2e tests
        run: mvn clean test -Dgroups=e2e
